name: scrape

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  scrape-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date        
        run: echo "{date}=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install project
        run: yarn
      - name: Run main script
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        run: node index.js
      - name: git status
        run: git status
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'feat(data): update data ${{ steps.date.outputs.date }}'
          committer: David Barton <theDavidBarton@users.noreply.github.com>
          body: |
            Updated data
            - Latest scraped data from ${{ steps.date.outputs.date }}
            - Auto-generated by the awesome [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          title: 'feat(data): update data ${{ steps.date.outputs.date }}'
          labels: data-update, automated pr
          assignees: theDavidBarton
          reviewers: theDavidBarton
          branch: update-data-${{ steps.date.outputs.date }}
